name: Bug Report
description: Report a problem with go-insert-locale
title: "[Bug]: "
labels:
  - bug

body:
  - type: checkboxes
    id: pre-requisites
    attributes:
      label: Pre-requisites
      description: |
          Make sure to check to see if you are following this requisites.
      options:
        - label: The issue is reproducible
          required: true
        - label: The aren't other issues similar to this problem.
          required: true
        - label: The aren't PRs tackling this problem.
          required: true

  - type: markdown
    attributes:
      value: |
        ## Issue report

  - type: textarea
    id: go-version
    attributes:
      label: Go version
      description: Paste here your Go version, `go version`.
      placeholder: |
        go version go1.24.1 darwin/arm64
    validations:
      required: true

  - type: dropdown
    id: operative-system
    attributes:
      label: Operative system
      description: OS in which the issue occurs
      multiple: true
      options:
        - Windows
        - MacOS
        - Linux
        - Android
        - All systems
    validations:
      required: true

  - type: textarea
    id: os-version
    attributes:
      label: OS version
      description: OS version in which the issue occurs
      placeholder: |
        MacOS 14.4.1
        Windows 11
        Ubuntu 22.04
        ...
    validations:
      required: true

  - type: textarea
    id: issue-behaviour
    attributes:
      label: Behaviour
      description: |
        Describe the current behaviour. May include logs, images, videos ...
    validations:
      required: true

  - type: textarea
    id: repro-steps
    attributes:
      label: Steps to reproduce
      description: List the steps to reproduce the behaviour mentioned above.
      placeholder: |
        1. `gil -input "locale_data.json -output ./locales/example-dir`
        ...
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Code of conduct agreement
      description: |
        By checking this I agree to [CODE OF CONDUCT](https://github.com/AlejandroSuero/go-insert-locale/blob/main/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct).
      options:
        - label: I agree and I am not violating the [CODE OF CONDUCT](https://github.com/AlejandroSuero/go-insert-locale/blob/main/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)
          required: true
